### ISSUE TITLE
llama-2-13b-chat does not expose a /docs endpoint 

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-services#128]
eg `http://54.194.138.5/llama-2-13b-chat/docs`

<img width="712" alt="image" src="https://github.com/premAI-io/prem-services/assets/3596602/06abe731-e0b3-4353-995a-c60ff6277742">

**Comment by filopedraz** [comment]
All of the expose it @tiero e.g., https://llama-2-13b-chat.demo.prem.ninja/docs
